---

networks:
  proxy:
    external: true

services:
  bazarr:
    container_name: yams-bazarr
    dns:
      - 192.168.10.2
    image: lscr.io/linuxserver/bazarr:latest
    volumes:
      - ./bazarr:/config
      - $NAS_PATH/media/tv:/tv
      - $NAS_PATH/media/movies:/movies
    environment:
      #- PUID=10000
      #- PGID=10000
      - TZ=Europe/Paris
    ports:
      - 6767
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.media.internal`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.service=bazarr-serv"
      - "traefik.http.services.bazarr-serv.loadbalancer.server.port=6767"
    networks:
      - proxy

  # Services to fetch indexers & index indexers ...
  prowlarr:
    dns:
      - 192.168.10.2
    container_name: yams-prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - ./prowlarr:/config
    environment:
      #- PUID=10000
      #- PGID=10000
      - TZ=Europe/Paris
    ports:
      - 9696
    restart: unless-stopped
    labels:
          # Prowlarr
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.media.internal`)"
      - "traefik.http.routers.prowlarr.service=prowlarr-serv"
      - "traefik.http.services.prowlarr-serv.loadbalancer.server.port=9696"
      # # TLS/websecure entrypoint      
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
    #network_mode: "container:gluetun_vpn"
    networks:
      - proxy

  sonarr:
    dns:
      - 192.168.10.2
    container_name: yams-sonarr
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - ./sonarr:/config
      - $NAS_PATH/media/tv:/tv
      - $NAS_PATH/torrents:/downloads
    environment:
      #- PUID=10000
      #- PGID=10000
      - TZ=Europe/Paris
    ports:
      - 8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.media.internal`)"
      - "traefik.http.routers.sonarr.service=sonarr-serv"
      - "traefik.http.services.sonarr-serv.loadbalancer.server.port=8989"
      # TLS/websecure entrypoint
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
    networks:
      - proxy

  radarr:
    dns:
      - 192.168.10.2
    container_name: yams-radarr
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - ./radarr:/config
      - $NAS_PATH/media/movies:/movies
      - $NAS_PATH/torrents:/downloads
    environment:
      #- PUID=10000
      #- PGID=10000
      - TZ=Europe/Paris
    ports:
      - 7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.media.internal`)"
      - "traefik.http.routers.radarr.service=radarr-serv"
      - "traefik.http.services.radarr-serv.loadbalancer.server.port=7878"
      # TLS/websecure entrypoint
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
    networks:
      - proxy

  # Services to manage requests for Jellyfin (media lib)
  jellyseerr:
    dns:
      - 192.168.10.2
    container_name: yams-jellyseerr
    image: fallenbagel/jellyseerr:latest
    volumes:
      - ./jellyseerr:/app/config
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
    ports:
      - 5055
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.media.internal`)"
      - "traefik.http.routers.jellyseerr.service=jellyseerr-serv"
      - "traefik.http.services.jellyseerr-serv.loadbalancer.server.port=5055"
      # TLS/websecure entrypoint
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls=true"
    networks:
      - proxy
