#version: "3"
networks:
  proxy:
    external: true

services:
  dozzle:
    image: "amir20/dozzle"
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.docker.internal`)"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.service=dozzle-serv"
      - "traefik.http.services.dozzle-serv.loadbalancer.server.port=8080"
    networks:
      - proxy

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=UTC    # optional: set desired timezone
      #user: UID:GID # optional: replace with your own user/group or uid/gid
    volumes:
      - ./ntfy/cache:/var/cache/ntfy
      - ./ntfy:/etc/ntfy
    ports:
      - 8008:80
    healthcheck: # optional: remember to adapt the host:port to your environment
      test: ["CMD-SHELL", "wget -q --tries=1 http://192.168.10.3:8008/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./uptimekuma:/app/data
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.docker.internal`)"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma-serv"
      - "traefik.http.services.uptime-kuma-serv.loadbalancer.server.port=3001"
    networks:
      - proxy
    restart: unless-stopped
