api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: websecure

#  websecure:
#    address: ":443"
#    http:
#      middlewares:
#        - secureHeaders@file
#      tls:
#        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: antochkamoul@gmail.com
#      storage: acme.json
#      keyType: EC384
#      httpChallenge:
#        entryPoint: web
