version: "3"

networks:
  proxy:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_vpn
    cap_add:
      - NET_ADMIN
    ports: #make sure to include these for qbittorrent to work
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_REGIONS=
    volumes:
      - ./gluetun_config:/gluetun
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gluetun.rule=Host(`qbittorrent.docker.internal`)"
      - "traefik.http.routers.gluetun.service=qbittorrent-serv"
      - "traefik.http.services.qbittorrent-serv.loadbalancer.server.port=6011"
      #- "traefik.http.routers.gluetun.entrypoints=websecure"
      #- "traefik.http.routers.gluetun.tls=true"
      #- "traefik.http.routers.gluetun.tls.certresolver=myresolver"
    networks:
      - proxy
